version: '3.8'

services:
  # MySQL Database Service
  
  db:
    image: mysql:8.0  # Or use another version, e.g., mysql:5.7
    container_name: yii2_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
    networks:
      - yii2_network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db  # Hostname of the MySQL server
      PMA_PORT: 3306  # Port of the MySQL server
      PMA_USER: yii2user  # MySQL user
      PMA_PASSWORD: yii2password  # MySQL user password
    ports:
      - "8081:80"  # Expose phpMyAdmin on port 8081
    networks:
      - yii2_network
  
  # MinIO Service
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin  # MinIO admin username
      MINIO_ROOT_PASSWORD: minioadmin  # MinIO admin password
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data  # Persist MinIO data
    networks:
      - yii2_network
    command: server /data --console-address ":9001"

volumes:
  db_data:
  minio_data: 

networks:
  yii2_network:
